@startuml

actor Администратор as admin

box "Frontend"
participant ЛК as lk
end box

box "Backend"
participant Accounting as a
participant Staff as s
end box

autonumber 1.1

==Создание проекта==

admin -> lk: Переходит к созданию карточки проекта

lk -> s: Получить список всех сотрудников
note right: Метод в разработке
s --> lk: Список всех сотрудников

lk --> admin: Отобразить форму для создания проекта

admin -> lk: Заполнить основные поля и подтвердить создание проекта
note left
    Название, описание,
    настройка статусов для типов задач
end note

lk -> lk: Проверить заполненность \nобязательных полей

break Заполнены не все обязательные поля
    lk --> admin: Уведомить о необходимости заполнения \nобязательных полей
end

lk-> lk: Провалидировать данные

break Некорректные данные
    lk --> admin: Уведомить о некорректных данных
end

lk -> a: Создание проекта

note right
    POST api/v1/accounting/projects
end note

a -> a: Проверить заполненность \nобязательных полей

break Заполнены не все обязательные поля
    a --> lk: [400] Заполнены не все обязательные поля
    lk --> admin: Уведомить об ошибке создания проекта
end

a-> a: Провалидировать данные

break Некорректные данные
    a --> lk: [400] Некорректные данные
    lk --> admin: Уведомить об ошибке создания проекта
end

a -> a: Создание проекта

break Проект с таким названием уже существует
a --> lk: [400] Проект с таким названием уже существует
lk --> admin: Уведомить об ошибке создания проекта
end

a --> lk: [201] Создание проекта
lk --> admin: Форма для назначения участников проекта

opt Фильтрация сотрудников по отделу
    admin -> lk: Настраивает фильтр по отделу
    lk -> s: Получить список сотрудник по фильтру
    note right: Метод в разработке
    s --> lk: Список сотрудников
end

opt Поиск сотрудников
    admin -> lk: Инициирует поиск сотрудников
    lk -> s: Получить список сотрудник по введенному значению
    note right: Метод в разработке
    s --> lk: Список сотрудников
end

admin -> lk: Переходит к назначению роли пользователям и \nподтверждает действие

lk -> lk: Проверить заполненность \nобязательных полей

break Заполнены не все обязательные поля
    lk --> admin: Уведомить о необходимости заполнения \nобязательных полей
end

lk -> lk: Провалидировать данные

break Некорректные данные
    lk --> admin: Уведомить о некорректных данных
end


lk -> a: Добавить участников проекта
note right: api/v1/accounting/projects/{project_id}/participants

a -> a: Проверить заполненность \nобязательных полей

break Заполнены не все обязательные поля
    a --> lk: [400] Заполнены не все обязательные поля
    lk --> admin: Уведомить об ошибке создания проекта
end

a -> a: Провалидировать данные

break Некорректные данные
    a --> lk: [400] Некорректные данные
    lk --> admin: Уведомить об ошибке создания проекта
end

a -> a: Добавление участников

alt Участники добавлены
a --> lk: [200] Участники добавлены
lk --> admin: Уведомить о добавлении участников
else Проект не найден
a --> lk: [404] Проект не найден
lk --> admin: Уведомить об ошибке добавления сотрудников
else Роль не найдена
a --> lk: [404] Роль не найдена
lk --> admin: Уведомить об ошибке добавления сотрудников
else Участник(-и) уже привязаны к проекту
a --> lk: [400] Участник(-и) уже привязаны к проекту
lk --> admin: Уведомить об ошибке добавления сотрудников
end

@enduml