@startuml

==Добавление участников к проекту==

autonumber 1.1

actor Администратор as admin
box "Frontend"
participant ЛК as lk
end box
box "Backend"
participant Staff as s
participant Accounting as a
end box

admin->lk: Переходит к добавлению участников к проекту

lk -> a: Получить данные проекта
note left: GET api/v1/accounting/projects/{projectId}

break Проект не найден
    a-->lk: [404] Проект не найден
    lk-->admin: Уведомить об ошибке редактирования проекта
end

a --> lk: Данные проекта

lk -> s: Получить данные участников проекта
 note right: GET api/v1/staff/employees-id/
s --> lk: Данные участников проекта

lk --> admin: Отобразить форму для редактирования участников проекта

opt Фильтрация сотрудников по отделу
    admin -> lk: Настраивает фильтр по отделу
    lk -> s: Получить список сотрудник по фильтру
    note right: Метод в разработке
    s --> lk: Список сотрудников
end

opt Поиск сотрудников
    admin -> lk: Инициирует поиск сотрудников
    lk -> s: Получить список сотрудник по введенному значению
    note right: Метод в разработке
    s --> lk: Список сотрудников
end

admin->lk: Внести изменения и подтвердить сохранение

lk -> lk: Проверить, что добавлен хотя бы один участник

break Пользователь не внес никаких изменений
    lk --> admin: Уведомить, что не внесены никакие изменения
end

lk -> lk: Проверить, что у добавленных участников заданы роли

break У участников не заданы роли
    lk --> admin: Уведомить, что у участников не заданы роли
end

lk->a: Добавить участников на проект
note right: PATCH \napi/v1/accounting/projects/{project_id}/participants

a-> a: Проверить, что у добавленных участников заданы роли

break Некорректные данные
    a --> lk: [400] У участников не заданы роли
    lk --> admin: Уведомить об ошибке добавления участников к проекту
end

a-> a: Провалидировать данные

break Некорректные данные
    a --> lk: [400] Некорректные данные
    lk --> admin: Уведомить об ошибке добавления участников к проекту
end

a->a: Сохранение изменений

alt Участники прикреплены к проекту
    a-->lk: Участники прикреплены к проекту
    lk-->admin: Уведомить о добавлении участников к проекту
else Участник(-и) уже прикреплен(-ы) к проекту
    a-->lk: [400] Участник(-и) уже прикреплен(-ы) к проекту
    lk-->admin: Уведомить об ошибке добавления участников к проекту
end

==Удаление участников с проекта==

autonumber 2.1

admin->lk: Переходит к удалению участников с проекта

lk -> a: Получить данные проекта
note left: GET api/v1/accounting/projects/{projectId}

break Проект не найден
    a-->lk: [404] Проект не найден
    lk-->admin: Уведомить об ошибке редактирования проекта
end

a --> lk: Данные проекта

lk -> s: Получить данные участников проекта
 note right: GET api/v1/staff/employees-id/
s --> lk: Данные участников проекта

lk --> admin: Отобразить форму для редактирования участников проекта

admin->lk: Внести изменения и подтвердить сохранение

lk -> lk: Проверить, что удален хотя бы один участник

break Пользователь не внес никаких изменений
    lk --> admin: Уведомить, что не внесены никакие изменения
end

lk->a: Удалить участников с проекта
note right: DELETE \napi/v1/accounting/projects/{project_id}/participants

a->a: Сохранение изменений

alt Участники удалены с проекта
    a-->lk: Участники удалены с проекта
    lk-->admin: Уведомить о удаления участников с проекта
else Участник не найден
    a-->lk: [400] Участник не найден
    lk-->admin: Уведомить об ошибке удаления участников с проекта
end

@enduml